//PRODUCT FEEDBACK ACTIONS
export const GET_PRODUCT_FEEDBACK = "GET_PRODUCT_FEEDBACK";
export const GET_ONE_PRODUCT_FEEDBACK = "GET_ONE_PRODUCT_FEEDBACK";
export const GET_PRODUCT_COMMENTS = "GET_PRODUCT_COMMENTS";
export const GET_COMMENT_REPLIES = "GET_COMMENT_REPLIES";
export const INCREASE_UPVOTE = "INCREASE_UPVOTE";
