//PRODUCT FEEDBACK ACTIONS
export const GET_PRODUCT_FEEDBACK = "GET_PRODUCT_FEEDBACK";
export const GET_ONE_PRODUCT_FEEDBACK = "GET_ONE_PRODUCT_FEEDBACK";
export const ADD_NEW_FEEDBACK = "ADD_NEW_FEEDBACK";
export const SORT_FEEDBACK = "SORT_FEEDBACK";
export const INCREASE_UPVOTE = "INCREASE_UPVOTE";
export const SET_EDIT_TO_TRUE = "SET_EDIT_TO_TRUE";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
export const GET_FEEDBACK_TO_DELETE = "GET_FEEDBACK_TO_DELETE";
export const CANCEL_DELETE = "CANCEL_DELETE";

//COMMENT ACTIONS
export const GET_PRODUCT_COMMENTS = "GET_PRODUCT_COMMENTS";
export const GET_COMMENT_REPLIES = "GET_COMMENT_REPLIES";

//AUTHENTICATION ACTIONS
export const REGISTER_NEW_USER = "REGISTER_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
